// Renders the home-screen icons, src/icons.ts and docs/icon-*.png. Run it with `npm run icons`.
//
// The icon is drawn here rather than taken from anywhere: two letters, PF, on a plain field. No
// manufacturer mark and no brand logo appears on it, because Partfinder is not affiliated with
// any of them.
//
// Only Node built-ins are used, and only zlib does any real work: the PNG encoder below is
// twenty lines because the format allows the simplest possible choices. Eight-bit truecolour,
// no interlacing, filter 0 on every row. A flat field with two letters compresses to a few
// hundred bytes that way, which is small enough to carry inside the Worker bundle.
//
// test/icons.test.ts fails when src/icons.ts or the committed PNGs no longer match what this
// renders, so the bytes the Worker serves are always the bytes this script produced.

import { deflateSync } from "node:zlib";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";

export const ICON_SIZES = [192, 512] as const;

/** THEME_COLOR_DARK from src/manifest.ts, as bytes: the page's dark background. */
export const ICON_BACKGROUND: readonly [number, number, number] = [0x11, 0x11, 0x11];
/** The dark scheme's --text. */
export const ICON_INK: readonly [number, number, number] = [0xf7, 0xf7, 0xf5];

/** Five by seven cells per letter, one blank column between them. */
const GLYPHS = [
  ["11111", "10001", "10001", "11110", "10000", "10000", "10000"], // P
  ["11111", "10000", "10000", "11110", "10000", "10000", "10000"], // F
];
const GLYPH_ROWS = 7;
const GLYPH_COLUMNS = GLYPHS.length * 5 + (GLYPHS.length - 1);

function crc32(bytes: Uint8Array): number {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit++) crc = crc & 1 ? (crc >>> 1) ^ 0xedb88320 : crc >>> 1;
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function chunk(type: string, data: Uint8Array): Uint8Array {
  const body = new Uint8Array(4 + data.length);
  for (let i = 0; i < 4; i++) body[i] = type.charCodeAt(i);
  body.set(data, 4);
  const out = new Uint8Array(8 + data.length + 4);
  new DataView(out.buffer).setUint32(0, data.length);
  out.set(body, 4);
  new DataView(out.buffer).setUint32(out.length - 4, crc32(body));
  return out;
}

/** True where the letters are, for a size-by-size grid. */
function isInk(size: number, x: number, y: number): boolean {
  const cell = Math.floor(size / 16);
  const left = Math.floor((size - GLYPH_COLUMNS * cell) / 2);
  const top = Math.floor((size - GLYPH_ROWS * cell) / 2);
  const column = Math.floor((x - left) / cell);
  const row = Math.floor((y - top) / cell);
  if (x < left || y < top || column < 0 || column >= GLYPH_COLUMNS || row < 0 || row >= GLYPH_ROWS) {
    return false;
  }
  const glyph = GLYPHS[Math.floor(column / 6)];
  const within = column % 6;
  return within < 5 && glyph !== undefined && glyph[row]?.[within] === "1";
}

/** One square PNG: 8-bit truecolour, no interlacing, filter 0 on every row. */
export function renderIcon(size: number): Uint8Array {
  const raw = new Uint8Array(size * (1 + size * 3));
  let at = 0;
  for (let y = 0; y < size; y++) {
    raw[at++] = 0; // filter: none
    for (let x = 0; x < size; x++) {
      const [r, g, b] = isInk(size, x, y) ? ICON_INK : ICON_BACKGROUND;
      raw[at++] = r!;
      raw[at++] = g!;
      raw[at++] = b!;
    }
  }

  const header = new Uint8Array(13);
  const view = new DataView(header.buffer);
  view.setUint32(0, size);
  view.setUint32(4, size);
  header[8] = 8; // bit depth
  header[9] = 2; // colour type: truecolour
  // bytes 10 to 12 stay 0: deflate, adaptive filtering, no interlacing.

  const parts = [
    new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", header),
    chunk("IDAT", new Uint8Array(deflateSync(raw, { level: 9 }))),
    chunk("IEND", new Uint8Array(0)),
  ];
  const png = new Uint8Array(parts.reduce((total, part) => total + part.length, 0));
  let offset = 0;
  for (const part of parts) {
    png.set(part, offset);
    offset += part.length;
  }
  return png;
}

export const ICONS_FILE = "src/icons.ts";
export const iconFile = (size: number) => `docs/icon-${size}.png`;

/** The generated module the Worker serves from, as text. */
export function renderIconsModule(): string {
  const constants = ICON_SIZES.map(
    (size) =>
      `/** ${size}x${size}, ${renderIcon(size).length} bytes. */\n` +
      `export const ICON_${size}_BASE64 =\n  "${Buffer.from(renderIcon(size)).toString("base64")}";`,
  );
  return [
    "// Generated by scripts/icons.ts. Do not edit; run `npm run icons`.",
    "//",
    "// The icons live here as base64 because a Worker has no filesystem: the bytes have to be in",
    "// the bundle. test/icons.test.ts fails if these stop matching what the script renders.",
    "",
    ...constants,
    "",
  ].join("\n");
}

const entry = process.argv[1];
if (entry !== undefined && import.meta.url === pathToFileURL(entry).href) {
  writeFileSync(ICONS_FILE, renderIconsModule());
  for (const size of ICON_SIZES) {
    mkdirSync(dirname(iconFile(size)), { recursive: true });
    writeFileSync(iconFile(size), renderIcon(size));
  }
  process.stdout.write(`wrote ${ICONS_FILE} and ${ICON_SIZES.length} icons\n`);
}
